# Change these first
owner: DeKs-Technology-Solutions-LLC # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: WhiteHorseVapor
    url: https://vapewh.com/
    assignees:
      - dekstech
      - Tizull
  - name: Blankz!
    url: https://blankzpods.com/
    assignees:
      - dekstech
      - Tizull

status-website:
  baseUrl: /uptime
  publish: true 
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: StatusPage
  introTitle: "**STATUS PAGE FOR DEKSTECH**"
  introMessage: Welcome to All Things Dekstech
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
